const CategoriesActionTypes = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const FoodsActionTypes = {
  FETCH_FOODS_START: 'FETCH_FOODS_START',
  FETCH_FOODS_SUCCESS: 'FETCH_FOODS_SUCCESS',
  FETCH_FOODS_FAILURE: 'FETCH_FOODS_FAILURE',
};

export { CategoriesActionTypes, FoodsActionTypes };
