const CategoriesActionTypes = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const MealsActionTypes = {
  FETCH_MEALS_START: 'FETCH_MEALS_START',
  FETCH_MEALS_SUCCESS: 'FETCH_MEALS_SUCCESS',
  FETCH_MEALS_FAILURE: 'FETCH_MEALS_FAILURE',
};

const IngredientsActionTypes = {
  FETCH_INGREDIENTS_START: 'FETCH_INGREDIENTS_START',
  FETCH_INGREDIENTS_SUCCESS: 'FETCH_INGREDIENTS_SUCCESS',
  FETCH_INGREDIENTS_FAILURE: 'FETCH_INGREDIENTS_FAILURE',
};

export { CategoriesActionTypes, MealsActionTypes, IngredientsActionTypes };
